### ISSUE TITLE
Merge range() and count()?

### ISSUE THREAD

**Issue by rauschma** [abozhilov/ES-Iter#8]
Have you considered giving `range()` the following signature?

```js
Iter.range(start=0, end=Infinity, step=1)
```

That way, you wouldn’t need `count()`, right?

I also find it more intuitive if `Iter.range(10)` starts at 10, instead of it being the upper boundary (similarly to how `Array.prototype.slice()` etc. work).

**Comment by abozhilov** [comment]
I've thought about it, but if `range(x)` is infinite generator, I'll confuse the people with Python background. 

Indeed the design of that function is not very JS-ish and it tends to confusion. Perhaps the compromised version of `range` is with mandatory `start`, `end`.  It will be closer to Ruby's ranges `(1..5).to_a # [1, 2, 3, 4, 5]`, where both `start` and `end` are mandatory. 

After this issue, I'll definitely implement the `count` using `range`.
Many thanks about your feedback. Much appreciated.

**Comment by rauschma** [comment]
Should we find out what JS programmers expect? I’ll do a Twitter poll.

**Comment by rauschma** [comment]
It looks like people expect this function to be overloaded!

```js
range(start)
range(start, end, step=1)
```

**Comment by abozhilov** [comment]
What do you think about mandatory `start` and `end`? I think it will be clever than Python's overloaded version of range.

**Comment by rauschma** [comment]
The more I think about that option, the more I like it. A 1-ary version of `range()` is just not intuitive enough.

**Comment by jouni-kantola** [comment]
In my opinion it can't get any cleaner than Haskell's list comprehensions.
`[ x | x [ <start>..<end>], predicate ]`
 I noticed array comprehensions were removed from Babel.js. Are comprehensions no longer a proposal?

However, regarding the question, I'd rather see something like:
```
range(start, takeUntil, predicate) //range(0, (val) => val < 10, (val) => val % 2 === 0)
range(start) //range(3) would return an infinite list starting from 3
```

**Comment by WebReflection** [comment]
what would be the primary use case for `rage` ?

If that's about arrays `for(let i of range(arr.length))` requires `0..(arr.length - 1)` iterations

Developers that use Python would eventually laugh at a `range` that differs from their

Developers from Bash will complain about being not inclusive as `0, 1, 2, 3` would be on `{0..3}` but they can get along with it

Almost nobody expects with a single argument to iterate from start to `Number.Infinity`, at least that's what the poll showed.

Finally, everyone used to [common utility belt libraries](https://lodash.com/docs#range) will fall into shenanigans.


Do we really need to reinvent the wheel? I hope no, and I think the following is just about right.

```js
range(start)
range(start, end, step=1)
```

**Comment by abozhilov** [comment]
I thought about `range` and seems Python has made huge design mess here.

1. The ranges are left closed. I think it's easier for people to understand the code, when the ranges are both left and right closed. If we suppose the opposite, that ranges are right closed, will you understand this by reading simply `range(0, 10)`?
I think the best decision for ranges are to be closed. Otherwise we are going to propagate bad design. Also ES is still open for Range type and range literals.

2. Formal definition of left closed range is `[a, b) = a <= x < b`. Python deviates and here with: `range(10, 0, -1)`. I think this should not be permitted.
I really hope JS to have separate Range type, which is iterable, have methods as `includes`, `reverse` etc. Ruby is a good example of ranges.  

Popular JS libs have already implemented `range` as almost 1 to 1 port of Python function. I think even `range` is landed in JS world it's still not used as often as in Python. The most often use-case in Python is to emulate C-ish loops e.g. `for i in range(10): print(i);`. The other use case is to iterate over the indexes of a list (which is noob way to do in Python): 

```python
arr = [1, 2, 3]; 
for i in range(len(arr)): 
    print(i, arr[i]);
``` 

By those common use cases, I consider Python's `range` is pythonic idiom. Personally I don't want to import it to the JS world. When `for-of` loops become common way to iterate in JS if we have `range` in this way we are going to import one more idiom in the language and it will brake TC39 from standardizing robust range type. 

I am going to change the range to:  `range(start, end, step = 1)` 

`start` and `end` are mandatory arguments and the interval is closed. 

As replacement of the idiom `range(X)` I'd like to have something like: 

```javascript
Iter.upTo(10); //  0, 1, 2, ... 9 
Iter.downFrom(10); // 9, 8, 7, ... 0 
``` 
I'm still open for proposal about the names of those.

**Comment by WebReflection** [comment]
will start and end be both inclusive? If the answer is yes, then we are in `{0..3}` bash land, not convenient or so handy with Arrays iterations. If the answer is that only start is inclusive, then I'd say noble intent, but the de-facto difference would be just having a mandatory `start`

`range(arr.length)` VS `range(0, arr.length)` ... I don't see the JS world saved much from anything.

What I believe is that programming should make developers life easier, instead of causing philosophical headaches every time something new, in a language, but well known everywhere else and for years in other languages/libraries where nobody complained much so far, is considered to be integrated.

This `range` case would be a no-brainer in a pragmatic approach, and there are polls showing developers expectations to confirm it.

You are free to improve, but I'd like to understand what is this `Iter.range` trying to solve that is so different from Python, what would be major use cases, where your choice shine in terms of disambiguation of intents.

Thanks

**Comment by rauschma** [comment]
API design is always full of compromises and uncertainties. But in this case, there is a clear precedent: lodash, which is quite popular in the JavaScript world. I’d ignore Python whenever lodash does something similar and copy what lodash does: https://lodash.com/docs#range

I also find range quite intuitive as a name, more so than `upTo()` and `downFrom()`.

**Comment by WebReflection** [comment]
Indeed lodash demonstrated that developers are already familiar with python-like `range` and everything is just fine.

**Comment by abozhilov** [comment]
OK guys, I did almost 1 to 1 copy of the lodash's `range`.  https://github.com/abozhilov/ES-Iter/blob/develop/src/Iter.js#L86 
As soon I reach 0.9.6 it will be merged in the master branch and I'll close this issue.

**Comment by abozhilov** [comment]
I still can't find use case of `range(10, 0, -1)` if it's intended to iterate in reverse usually we do it to 0 inclusive. Probably the most common use case would be `range(arr.length - 1, -1, -1)` which is ugly in my opinion. 

What do you think if range does not allow negative `step` value? Instead, we can have: `rangeRight()` which will be fully compatible with `range` but it yields in reversed order the integers. 

`range(5)` 0, 1, 2, 3, 4
`rangeRight(5)` 4, 3, 2, 1, 0

**Comment by rauschma** [comment]
Intriguing observation! I’d postpone creating `rangeRight`, even though it would solve this problem neatly. `reversedRange` or something similar may be a better name.

**Comment by rauschma** [comment]
`rangeReversed` is another possibility.

**Comment by abozhilov** [comment]
`reversedRange` definitely makes more sense, especially for Python's devs. I used `rangeRight` to be consistence with built-in JS API e.g. `reduceRight`. I'm still not convinced about its name. Until v.1.0.0 I will definitely reconsider that name.
